Fixing error calling replace on non string
when providing a `pathname` array, if one of the array values is an integer, a TypeError will be thrown:

`TypeError: undefined is not a function`

this is due to the `replace`.  Suggesting to convert to string first